Update 2_📈_Logistic_Regression.py
Put try and exception for Import error in Missing values

ImportError: cannot import name '_MissingValues' from 'sklearn.utils._param_validation'